package com.alura.home.enums;

public enum TemperatureConversionTypes {
    CELSIUS_TO_KELVIN,
    CELSIUS_TO_FAHRENHEIT,
    FAHRENHEIT_TO_CELSIUS,
    FAHRENHEIT_TO_KELVIN,
    KELVIN_TO_CELSIUS,
    KELVIN_TO_FAHRENHEIT,
    FAHRENHEIT_TO_FAHRENHEIT,
    CELSIUS_TO_CELSIUS,
    KELVIN_TO_KELVIN
}